model:
  arch: simple
  backbone: resnet
  preset: BASIC_FLOW   # See src/synth/synth_presets.py for more options
  num_workers: 4
  batch_size: 64
  num_epochs: 120

  optimizer:
    base_lr: 1e-4
    optimizer: adam
    scheduler: cosine

loss:
  parameters_loss_type: L1        # One of L1, L2
  parameters_loss_weight: 1

  spectrogram_loss_warmup_epochs: 120
  loss_switch_epochs: 0
  in_domain_epochs: 120

synth:
  preset: BASIC_FLOW
  transform: MEL                  # One of MEL, SPEC
  use_multi_spec_input: false     # Whether to use multi fft spectrograms as input to the model
  signal_duration: 4.0
  note_off_time: 3.0
  added_noise_std: 0.001          # Std of noise added to input sounds (0 to disable)

logging:
  n_images_to_log: 5              # Number of samples to log to tensorboard each epoch
