model:
  arch: simple
  backbone: resnet
  preset: BASIC_FLOW   # See src/synth/synth_presets.py for more options
  num_workers: 4
  batch_size: 64
  num_epochs: 120

  optimizer:
    base_lr: 1e-4
    optimizer: adam
    scheduler: cosine

loss:
  parameters_loss_type: L1        # One of L1, L2
  parameters_loss_weight: 0.1

  spec_loss_type: SPECTROGRAM     # one of SPECTROGRAM, MEL_SPECTROGRAM or BOTH
  preset: cumsum_time             # DDSP spectral loss composition and configuration. See src/model/loss/spectral_loss_presets.py
  control_spec_preset: cumsum_time
  spectrogram_loss_weight: 0.001

  spectrogram_loss_warmup_epochs: 15     # Warmup epochs - only parameter loss will be used
  loss_switch_epochs: 45                 # Switch epochs - parameters loss and spectral loss will gradually switch
  min_parameters_loss_decay: 0           # Minimum scale of param loss decay. 0 - model will train on spec loss only after switch, 1 - spec loss and params loss will have equal weight
  in_domain_epochs: 120

  use_chain_loss: false
  use_gradual_chain_loss: false

synth:
  preset: BASIC_FLOW
  transform: MEL                  # One of MEL, SPEC
  use_multi_spec_input: false     # Whether to use multi fft spectrograms as input to the model
  signal_duration: 4.0
  note_off_time: 3.0
  added_noise_std: 0.001          # Std of noise added to input sounds (0 to disable)

logging:
  n_images_to_log: 5              # Number of samples to log to tensorboard each epoch
