model:
  arch: simple
  backbone: gru
  chain: REDUCED_SIMPLE_OSC
  num_workers: 8
  batch_size: 64
  num_epochs: 200
#  ckpt_path: 'C:\Users\noamk\PycharmProjects\ai_synth\src\my_checkpoints\version_6\epoch=80-train_loss=1.77.ckpt'

  optimizer:
    base_lr: 0.001
    optimizer: adam
    scheduler: exponential
    gamma: 0.99

loss:
  loss_preset: cumsum_time
  control_spec_preset: cumsum_time
  parameters_loss_norm: L1

  apply_loss_normalization: true
  parameters_loss_weight: 1
  spectrogram_loss_weight: 0

  spectrogram_loss_warmup_epochs: 3333333333333333
  loss_switch_epochs: 0
  min_parameters_loss_decay: 0
  in_domain_epochs: 200

  use_chain_loss: false
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  chain: REDUCED_SIMPLE_OSC
  transform: MEL
  apply_log_transform_to_input: true
  use_multi_spec_input: false
  signal_duration: 4.0
  note_off_time: 3.0
  added_noise_std: 0.0001

logging:
  n_images_to_log: 5
