model:
  arch: simple
  backbone: resnet
  preset: REDUCED_SIMPLE_FILTER
  num_workers: 8
  batch_size: 64
  num_epochs: 60

  optimizer:
    base_lr: 0.005
    optimizer: adam
    scheduler: exponential
    gamma: 0.99

loss:
  spec_loss_type: SPECTROGRAM
  preset: cumsum_time
  control_spec_preset: cumsum_freq
  parameters_loss_type: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0

  spectrogram_loss_warmup_epochs: 10
  loss_switch_epochs: 20
  min_parameters_loss_decay: 0
  in_domain_epochs: 30

  use_chain_loss: true
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  preset: REDUCED_SIMPLE_FILTER
  transform: MEL
  use_multi_spec_input: false
  signal_duration: 1
  note_off_time: 0.75
  added_noise_std: 0.001

logging:
  n_images_to_log: 5
