model:
  arch: simple
  backbone: gru
  chain: MODULAR
  num_workers: 8
  batch_size: 64
  num_epochs: 200

  optimizer:
    base_lr: 0.005
    optimizer: adam
    scheduler: exponential
    gamma: 0.99

loss:
  preset: cumsum_time
  control_spec_preset: cumsum_time
  parameters_loss_norm: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.0001

  spectrogram_loss_warmup_epochs: 25
  loss_switch_epochs: 75
  min_parameters_loss_decay: 0
  in_domain_epochs: 100

  use_chain_loss: false
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  chain: MODULAR
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 4
  note_off_time: 3.0
  added_noise_std: 0.001

logging:
  n_images_to_log: 5
