model:
  arch: simple
  backbone: resnet
  chain: LFO_SAW
  num_workers: 4
  batch_size: 10
  num_epochs: 60

  optimizer:
    base_lr: 2e-4
    optimizer: adam
    scheduler: cosine

loss:
  loss_preset: mag_logmag
  control_spec_preset: cumsum_freq
  parameters_loss_norm: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.001

  spectrogram_loss_warmup_epochs: 10000
  loss_switch_epochs: 10000
  min_parameters_loss_decay: 0
  in_domain_epochs: 60

  use_chain_loss: true
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  chain: LFO_SAW
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 1.0
  note_off_time: 0.75
  added_noise_std: 0.001

logging:
  n_images_to_log: 5
