model:
  arch: simple
  backbone: resnet
  preset: MODULAR
  num_workers: 4
  batch_size: 50
  num_epochs: 200
  learning_rate: float = 3e-4

loss:
  spec_loss_type: SPECTROGRAM
  preset: cumsum_time
  parameters_loss_type: L1

  parameters_loss_weight: 0.01
  spectrogram_loss_weight: 0.01

  spectrogram_loss_warmup: 40 * 1000
  loss_switch_steps: 40 * 1000
  min_parameters_loss_decay: 0.01

  use_chain_loss: true
  chain_loss_weight: 1.0

synth:
  preset: MODULAR
  signal_duration: 4
  note_off_time: 3.0

logging:
  n_images_to_log: 5
