model:
  arch: simple
  backbone: resnet
  preset: MODULAR
  num_workers: 0
  batch_size: 75
  num_epochs: 200

  optimizer:
    base_lr: 1e-4
    optimizer: adam
    scheduler: constant

loss:
  spec_loss_type: SPECTROGRAM
  preset: cumsum_time
  parameters_loss_type: L1

  parameters_loss_weight: 0.01
  spectrogram_loss_weight: 0.01

  spectrogram_loss_warmup: 40000
  loss_switch_steps: 40000
  min_parameters_loss_decay: 0.01

  use_chain_loss: true
  chain_loss_weight: 1.0

synth:
  preset: MODULAR
  transform: MEL
  signal_duration: 4
  note_off_time: 3.0

logging:
  n_images_to_log: 2
