model:
  arch: simple
  backbone: resnet
  preset: MODULAR
  num_workers: 4
  batch_size: 16
  num_epochs: 200

  resume_training: /home/almogelharar/almog/ai_synth/experiments/baseline_old_fltr_full_range_w_noise/checkpoints/last.ckpt

  optimizer:
    base_lr: 0.005
    optimizer: adam
    scheduler: exponential
    gamma: 0.99

loss:
  spec_loss_type: SPECTROGRAM
  preset: mag_logmag
  control_spec_preset: cumsum_freq
  parameters_loss_type: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0

  spectrogram_loss_warmup: 3333333333333333
  loss_switch_steps: 0
  min_parameters_loss_decay: 0
  in_domain_epochs: 200

  use_chain_loss: true
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  preset: MODULAR
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 4
  note_off_time: 3.0
  added_noise_std: 0.001

logging:
  n_images_to_log: 5
