model:
  arch: simple
  backbone: gru
  chain: REDUCED_SIMPLE_FILTER
  num_workers: 0
  batch_size: 10
  num_epochs: 120

  optimizer:
    base_lr: 0.005
    optimizer: adam
    scheduler: exponential
    gamma: 0.99

loss:
  loss_preset: mag_logmag
  control_spec_preset: cumsum_freq
  parameters_loss_norm: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.0001

  spectrogram_loss_warmup_epochs: 15
  loss_switch_epochs: 45
  min_parameters_loss_decay: 0
  in_domain_epochs: 120

  use_chain_loss: true
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  chain: REDUCED_SIMPLE_FILTER
  transform: MEL
  use_multi_spec_input: False
  signal_duration: 4
  note_off_time: 3.0
  added_noise_std: 0.001

logging:
  n_images_to_log: 5
