model:
  arch: simple
  backbone: resnet
  chain: MODULAR
  num_workers: 4
  batch_size: 50
  num_epochs: 175
  ckpt_path: C:\Users\user\PycharmProjects\ai_synth\experiments\old_filter\last.ckpt

  optimizer:
    base_lr: 1e-5
    optimizer: adam
    scheduler: cosine

loss:
  preset: cumsum_time
  control_spec_preset: cumsum_freq
  parameters_loss_norm: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.001

  spectrogram_loss_warmup_epochs: 0
  loss_switch_epochs: 75000
  min_parameters_loss_decay: 0
  in_domain_epochs: 200

  use_chain_loss: false
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 0

synth:
  chain: MODULAR
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 4
  note_off_time: 3.0
  added_noise_std: 0

logging:
  n_images_to_log: 5
