model:
  arch: simple
  backbone: resnet
  preset: MODULAR
  num_workers: 4
  batch_size: 50
  num_epochs: 200

  optimizer:
    base_lr: 1e-4
    optimizer: adam
    scheduler: cosine

loss:
  loss_preset: cumsum_time
  control_spec_preset: cumsum_freq
  parameters_loss_norm: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.001

  dataset_size: 50000
  spectrogram_switch_epoc_start: 25
  spectrogram_switch_epoc_end: 75
  gradual_chain_warmup_epochs: 5

  spectrogram_loss_warmup_epochs: 50
  loss_switch_epochs: 150
  min_parameters_loss_decay: 0
  in_domain_epochs: 200

  use_chain_loss: true
  chain_loss_weight: 1.0
  use_gradual_chain_loss: true
  # chain_warmup_factor shall be defined by (dataset_size / batch_size) * gradual_chain_warmup_epochs
  chain_warmup_factor: 5000

synth:
  preset: MODULAR
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 4
  note_off_time: 3.0
  added_noise_std: 0.001

logging:
  n_images_to_log: 5
