model:
  arch: simple
  backbone: resnet
  preset: MODULAR
  num_workers: 4
  batch_size: 4
  num_epochs: 200

  optimizer:
    base_lr: 1e-4
    optimizer: adam
    scheduler: cosine

loss:
  spec_loss_type: SPECTROGRAM
  preset: cumsum_time
  parameters_loss_type: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.001

  spectrogram_loss_warmup: 312500
  loss_switch_steps: 75000
  min_parameters_loss_decay: 0
  in_domain_epochs: 200

  use_chain_loss: true
  chain_loss_weight: 1.0

synth:
  preset: MODULAR
  transform: MEL
  signal_duration: 4
  note_off_time: 3.0
  added_noise_std: 0.001

logging:
  n_images_to_log: 5
