model:
  arch: simple
  backbone: resnet
  preset: MODULAR_NEW
  num_workers: 4
  batch_size: 32
  num_epochs: 200
  ckpt_path: C:\Users\user\PycharmProjects\ai_synth\experiments\new_filter\checkpoints\last.ckpt

  optimizer:
    base_lr: 1e-5
    max_lr: 1e-4
    optimizer: adam
    scheduler: cyclic
    cyclic_step_size_up: 6250


loss:
  spec_loss_type: SPECTROGRAM
  preset: cumsum_time
  control_spec_preset: cumsum_freq
  parameters_loss_type: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.001

  spectrogram_loss_warmup: 0
  loss_switch_steps: 156250
  min_parameters_loss_decay: 0
  in_domain_epochs: 200

  use_chain_loss: true
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  preset: MODULAR_NEW
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 4
  note_off_time: 3.0
  added_noise_std: 0

logging:
  n_images_to_log: 5
