model:
  arch: simple
  backbone: resnet
  chain: MODULAR_NEW
  num_workers: 4
  batch_size: 10
  num_epochs: 200

  optimizer:
    base_lr: 3e-4
    optimizer: adam
    scheduler: constant

loss:
  spec_loss_type: SPECTROGRAM
  preset: mag_logmag
  control_spec_preset: cumsum_freq
  parameters_loss_type: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.01

  spectrogram_loss_warmup_epochs: 125000
  loss_switch_epochs: 375000
  min_parameters_loss_decay: 0
  in_domain_epochs: 200

  use_chain_loss: true
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  chain: MODULAR_NEW
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 4
  note_off_time: 3.0

logging:
  n_images_to_log: 5
