model:
  arch: simple
  backbone: resnet
  preset: LFO_SIN
  num_workers: 4
  batch_size: 4
  num_epochs: 50

  optimizer:
    base_lr: 3e-4
    optimizer: adam
    scheduler: cosine

loss:
  spec_loss_type: BOTH
  preset: cumsum_freq
  control_spec_preset: cumsum_freq
  parameters_loss_type: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.001

  spectrogram_loss_warmup_epochs: 0
  loss_switch_epochs: 0
  min_parameters_loss_decay: 0
  in_domain_epochs: 500

  use_chain_loss: false
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  preset: LFO_SIN
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 4.0
  note_off_time: 3.0
  added_noise_std: 0.001

logging:
  n_images_to_log: 4
