model:
  arch: simple
  backbone: resnet
  preset: SAW_SQUARE_MIX_FILTER
  num_workers: 0
  batch_size: 1
  num_epochs: 500
  train_single_param: True
  single_param_to_train: freq

  optimizer:
    base_lr: 1e-4
    optimizer: sgd
    scheduler: constant

loss:
  spec_loss_type: SPECTROGRAM
  preset: cumsum_time
  control_spec_preset: cumsum_freq
  parameters_loss_type: L1

  parameters_loss_weight: 0.1
  spectrogram_loss_weight: 0.001

  spectrogram_loss_warmup: 0
  loss_switch_steps: 0
  min_parameters_loss_decay: 0
  in_domain_epochs: 500

  use_chain_loss: true
  chain_loss_weight: 1.0
  use_gradual_chain_loss: false
  chain_warmup_factor: 5

synth:
  preset: SAW_SQUARE_MIX_FILTER
  transform: MEL
  use_multi_spec_input: True
  signal_duration: 1.0
  note_off_time: 0.75
  added_noise_std: 0.001

logging:
  n_images_to_log: 0
